name: release-management-commands
runs:
  using: composite
  steps:
#   # This item has no matching transformer
#   - salesforce_npm_release_management_sign:
#   # This item has no matching transformer
#   - salesforce_npm_release_management_publish:
  - name: Wait for version to become available on NPM registry
    run: |-
      PKG_NAME=$(cat package.json | jq -r .name)
      PKG_VERSION=$(cat package.json | jq -r .version)
      MAX_TRIES=30
      TRIES=0
      until (( $(curl -s 'https://registry.npmjs.org/'$PKG_NAME | jq '.["versions"]["'$PKG_VERSION'"]' | grep -c $PKG_VERSION ) )) || (($TRIES >= $MAX_TRIES )); do
          printf '.'
          sleep 1
          TRIES=$((TRIES+1))
      done
      if (($TRIES >= $MAX_TRIES)); then
          echo "Timeout waiting for tag. Exiting job"
          exit 1
      fi
    shell: bash
#   # This item has no matching transformer
#   - salesforce_npm_release_management_verify_signed_package: